### ISSUE TITLE
Travis-CI testing and Docker error?

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#101]
I noticed that my changes are sometimes failing Travis-CI with this message:

> The command "docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci" exited with 5.

e.g. here: https://travis-ci.org/gaocegege/Processing.R/builds/240249559?utm_source=github_status&utm_medium=notification

Why are we using docker here -- and is there anything in particular I should do about this in my local setup, or any particular cause?

**Comment by gaocegege** [comment]
We run coala check in Docker, so it is caused by coala: https://travis-ci.org/gaocegege/Processing.R/builds/240249559#L3654

The code is not in formatR format, but it doesn't matter. If you have coala in your local env, just run coala and it has a option to apply the patches to fix these errors.

And it doesn't matter, since I can fix these errors for you :-)

**Comment by jeremydouglass** [comment]
Ah, I see, thank you. I was focusing on the docker part, and skimming over the coala reports because they were marked with [INFO] -- I see now that there are lots of small whitespace errors that are causing the check to fail, like `t <- i / steps` vs `t <- i/steps`. 

I can install coala locally using docker. Very long term the best clean contribution solution for casual Processing.R authors will eventually to bind the CMD-T in PDE to a syntax cleanup, like in Java mode.

**Comment by gaocegege** [comment]
Yeah, cmd T is helpful, and we have a issue: #84 

:smile:
