### ISSUE TITLE
Import netlify to CI the reference docs

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#199]
ref https://www.netlify.com/docs/continuous-deployment/

**Comment by jeremydouglass** [comment]
Great!

I haven't used netlify before -- it looks like netlify doesn't need a config file present in https://github.com/processing-r/processing-r.github.io/ in order to run. Was it set up entirely through your gaocegege account credentials in the netlify interface?

If inn the future there ends up being a maintainer transfer to Processing then we may want to make a list of account-based integrations like this one that you would switch over.

**Comment by gaocegege** [comment]
Yeah, the documentation is a static site so there is no need to config netlify. But we do need the list.
