### ISSUE TITLE
Get in touch with Processing "modes" community

### ISSUE THREAD

**Issue by jeremydouglass** [gaocegege/Processing.R#56]
@gaocegege -- There is community of people who have recently developed either:

1. the code that enables modes in PDE
2. a mode for Processing, such as:
    -  Processing.py https://github.com/jdf/processing.py @jdf
    -  p5.js https://github.com/processing/p5.js @lmccart
    -  Android Mode https://github.com/processing/processing-android @codeanticode
    -  REPL mode https://github.com/joelmoniz/REPLmode @joelmoniz
    -  CoffeeScript mode https://github.com/fjenett/coffeescript-mode-processing @fjenett
    -  ...Processing.js / JavaScript mode, JRubyArt, etc.

As part of your GSOC "community bonding" period I would suggest first taking a look at these other mode repos, then reaching out to Processing mode experts, *briefly* introducing yourself and your project, and perhaps asking if they have any general words of wisdom for developing a new mode. As with #34 with the R community, if anyone from the "modes" community is interested they might also be kind enough to give more detailed feedback on the work plan.

**Comment by gaocegege** [comment]
Hi, all

processing.py is a great reference implementation. I designed a similar architecture for Processing.R just like it. And other modes will be helpful, too. There is little documentation about Processing mode implementation, so the existing modes is important to me :)

**Comment by gaocegege** [comment]
And https://github.com/galsasson/TweakMode is also a GSoC project which implements a new mode for Processing's PDE that allows modifying fixed numbers in the code while the sketch is running and seeing the result in real-time.

**Comment by jdf** [comment]
The design of Python Mode is dictated by two considerations:

1. The runtime is the real (Java) Processing runtime. To the extent possible, every function named in the Processing reference is executed by the Java implementation.
2. It's really, really slow to start up the Jython interpreter and populate it with all of the required pseudo-builtins (Processing keywords).

Both of these considerations lead to a lot of distortions that may not be necessary in another mode, so keep that in mind. For example, the sketch runner is a long-running application that communicates with its editor via TCP/IP.

I'd be willing to take at least a quick look at your plans, but any opinion I could offer should be taken with care, since I know nothing at all about R!

**Comment by gaocegege** [comment]
Thanks for the comments, I refer the design of sketch runner although I don't know why it is designed to this. Now get it 🤔

**Comment by gaocegege** [comment]
Now R is not a big part in this mode, it is handled mostly by renjin which is a JVM interpreter for R just like jython. Thanks for your kindness 😄

**Comment by jeremydouglass** [comment]
Processing.R was supported by expert advice, has been accepted to the PDE Contributions Manager, and has a post in the Modes channel of the Processing forum. Getting in touch: successful!
